---
- hosts: eoi-server1
  vars_files:
    - vars.yml

  tasks:
    - name: hacer un ping
      ping:
        
    - name: mostrar el nombre de la máquina
      debug:
        msg: "Nombre de la máquina {{ ansible_hostname }}"

    - name: Hacer un git clone del repo
      git:
        repo: https://github.com/EliasLopezBouzid/my-first-blog.git
        dest: "{{project_path}}"
        force: true

    - name: Crear entorno virtual e instalar requirements
      pip:
        requirements: "{{project_path}}/requirements.txt"
        virtualenv: "{{venv}}"

    - name: Hacer y aplicar migraciones Django
      django_manage:
        command: migrate
        project_path: "{{project_path}}"
        virtualenv: "{{venv}}"

    - name: Cargar datos inciales en la base de datos
      django_manage:
        command: loaddata
        project_path: "{{project_path}}"
        fixtures: "{{project_path}}/db.json"
        virtualenv: "{{venv}}"

    - name: Comprobando si superuser admin existe
      django_manage:
        command: shell -c 'import sys; from django.contrib.auth.models import User; sys.exit(0 if User.objects.filter(username="admin").count() > 0 else 1)'
        virtualenv: "{{venv}}"
        project_path: "{{project_path}}" 
      register: checksuperuser

    - name: Creando superusergit admin (Sin password)
      django_manage:
        command: "createsuperuser --noinput --username=admin2 --email=e.lopezbouzid.com DJANGO_SUPERUSER_PASSWORD=12345"
        project_path: "{{project_path}}"
        virtualenv: "{{venv}}"
      when: checksuperuser.out|trim == "0"

